/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.SistemaMuseo;
import disenno.ExposicionesTableModel;
import java.awt.Cursor;
import static java.awt.Frame.HAND_CURSOR;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import modelo.Administrador;
import modelo.Exposicion;
import modelo.Guia;

/**
 *
 * @author Guillermo y Victor
 */
public class MenuAdministradorFrame extends javax.swing.JFrame {

    private Administrador a;
    private List<Guia> empleados;
    private List<Exposicion> exposiciones;
    private SistemaMuseo sm;
    private ExposicionesTableModel etm;
    private DefaultTableModel plantilla;
    private final String[] cabeceraPlantilla = {"ID", "Nombre", "DNI", "Teléfono"};

    /**
     * Creates new form MenuAdministradorFrame
     *
     * @param a
     */
    public MenuAdministradorFrame(Administrador a) {
        this.a = a;
        empleados = a.getEmpleados();
        exposiciones = a.getExposiciones();
        etm = new ExposicionesTableModel(exposiciones);

        initComponents();
        componentesIniciales();
    }

    public MenuAdministradorFrame() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorArchivos = new javax.swing.JFileChooser();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelEmpleados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfDNI = new javax.swing.JTextField();
        tfClave = new javax.swing.JTextField();
        tfTelf = new javax.swing.JTextField();
        tfNSS = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfNGuia = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btEliminarGuia = new javax.swing.JButton();
        btAnnadirGuia = new javax.swing.JButton();
        panelExposiciones = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaExposiciones = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        botonAbrirExpo = new javax.swing.JButton();
        botonAddExpo = new javax.swing.JButton();
        botonDropExpo = new javax.swing.JButton();
        botonModificarExpo = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        campoNombreExpo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoDuracion = new javax.swing.JTextField();
        campoRuta = new javax.swing.JTextField();
        botonAbrirSelector = new javax.swing.JLabel();
        infoErrorExpo = new javax.swing.JLabel();
        oblig1 = new javax.swing.JLabel();
        oblig2 = new javax.swing.JLabel();
        oblig3 = new javax.swing.JLabel();
        panelEntradas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        campoPrecioEntrada = new javax.swing.JTextField();
        botonCambiarPrecioEntrada = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        campoPrecioSuplemento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        botonCambiarSuplemento = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mostrarGestionEmpleados = new javax.swing.JMenuItem();
        mostrarGestionExposiciones = new javax.swing.JMenuItem();
        mostrarGestionEntradas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MuseoPalentinoApp - Menú de Administrador");
        setIconImage(getIconImage());
        setResizable(false);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        tablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaEmpleados);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Datos del Empleado  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel1.setText("Nombre del empleado:");

        jLabel2.setText("DNI:");

        jLabel3.setText("Clave provisional:");

        jLabel4.setText("Teléfono:");

        jLabel5.setText("Nº Seguridad Social:");

        jLabel10.setText("Nº Guía:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(tfNGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tfNSS)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfClave)
                            .addComponent(tfNombre))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Opciones de Empleado  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(182, 204));

        btEliminarGuia.setText("Eliminar Guía");
        btEliminarGuia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btEliminarGuiaMouseEntered(evt);
            }
        });
        btEliminarGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarGuiaActionPerformed(evt);
            }
        });

        btAnnadirGuia.setText("Añadir Guía");
        btAnnadirGuia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btAnnadirGuiaMouseEntered(evt);
            }
        });
        btAnnadirGuia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAnnadirGuiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btEliminarGuia, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(btAnnadirGuia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btAnnadirGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btEliminarGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelEmpleadosLayout = new javax.swing.GroupLayout(panelEmpleados);
        panelEmpleados.setLayout(panelEmpleadosLayout);
        panelEmpleadosLayout.setHorizontalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelEmpleadosLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelEmpleadosLayout.setVerticalGroup(
            panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmpleadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLayeredPane1.add(panelEmpleados, "card2");

        tablaExposiciones.setModel(etm);
        jScrollPane2.setViewportView(tablaExposiciones);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Opciones de Exposición  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        botonAbrirExpo.setText("Abrir Exposición");
        botonAbrirExpo.setPreferredSize(new java.awt.Dimension(150, 23));
        botonAbrirExpo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAbrirExpoMouseEntered(evt);
            }
        });
        botonAbrirExpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirExpoActionPerformed(evt);
            }
        });

        botonAddExpo.setText("Añadir Exposición");
        botonAddExpo.setPreferredSize(new java.awt.Dimension(150, 23));
        botonAddExpo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAddExpoMouseEntered(evt);
            }
        });
        botonAddExpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddExpoActionPerformed(evt);
            }
        });

        botonDropExpo.setText("Eliminar Exposición");
        botonDropExpo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonDropExpoMouseEntered(evt);
            }
        });
        botonDropExpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDropExpoActionPerformed(evt);
            }
        });

        botonModificarExpo.setText("Modificar Exposición");
        botonModificarExpo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonModificarExpoMouseEntered(evt);
            }
        });
        botonModificarExpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarExpoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAbrirExpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonAddExpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonDropExpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonModificarExpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonAbrirExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonAddExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonDropExpo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonModificarExpo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Datos de Exposición  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel6.setText("Nombre de la exposición:");

        jLabel8.setText("Duración del recorrido:");
        jLabel8.setToolTipText("");

        jLabel11.setText("Ruta de imagen (máx. 300x114 px):");
        jLabel11.setToolTipText("");

        botonAbrirSelector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/iconos/carpeta.png"))); // NOI18N
        botonAbrirSelector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMouseReleased(evt);
            }
        });

        infoErrorExpo.setForeground(java.awt.Color.red);
        infoErrorExpo.setText(" ");

        oblig1.setBackground(new java.awt.Color(255, 255, 255));
        oblig1.setForeground(new java.awt.Color(255, 0, 102));
        oblig1.setText(" ");

        oblig2.setBackground(new java.awt.Color(255, 255, 255));
        oblig2.setForeground(new java.awt.Color(255, 0, 102));
        oblig2.setText(" ");

        oblig3.setBackground(new java.awt.Color(255, 255, 255));
        oblig3.setForeground(new java.awt.Color(255, 0, 102));
        oblig3.setText(" ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoErrorExpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oblig1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(campoNombreExpo, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oblig2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(campoDuracion))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(oblig3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(campoRuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAbrirSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(campoNombreExpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oblig1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oblig2)
                        .addComponent(campoDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(oblig3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAbrirSelector))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoErrorExpo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout panelExposicionesLayout = new javax.swing.GroupLayout(panelExposiciones);
        panelExposiciones.setLayout(panelExposicionesLayout);
        panelExposicionesLayout.setHorizontalGroup(
            panelExposicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExposicionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExposicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(panelExposicionesLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelExposicionesLayout.setVerticalGroup(
            panelExposicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExposicionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelExposicionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelExposiciones, "card3");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Datos de Entrada  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel12.setText("Precio entrada:");

        botonCambiarPrecioEntrada.setText("Cambiar Precio");
        botonCambiarPrecioEntrada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCambiarPrecioEntradaMouseEntered(evt);
            }
        });
        botonCambiarPrecioEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarPrecioEntradaActionPerformed(evt);
            }
        });

        jLabel16.setText("Suplemento guia:");

        jLabel17.setText("€");

        botonCambiarSuplemento.setText("Cambiar Suplemento");
        botonCambiarSuplemento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCambiarSuplementoMouseEntered(evt);
            }
        });
        botonCambiarSuplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarSuplementoActionPerformed(evt);
            }
        });

        jLabel18.setText("€");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(campoPrecioSuplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCambiarSuplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(campoPrecioEntrada)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCambiarPrecioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(campoPrecioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCambiarPrecioEntrada)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(campoPrecioSuplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(botonCambiarSuplemento))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelEntradasLayout = new javax.swing.GroupLayout(panelEntradas);
        panelEntradas.setLayout(panelEntradasLayout);
        panelEntradasLayout.setHorizontalGroup(
            panelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelEntradasLayout.setVerticalGroup(
            panelEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradasLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );

        jLayeredPane1.add(panelEntradas, "card4");

        jMenu1.setText("Opciones");

        menuCerrarSesion.setText("Cerrar sesión");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(menuCerrarSesion);

        jMenuBar.add(jMenu1);

        jMenu2.setText("Gestión de...");

        mostrarGestionEmpleados.setText("Empleados");
        mostrarGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarGestionEmpleadosActionPerformed(evt);
            }
        });
        jMenu2.add(mostrarGestionEmpleados);

        mostrarGestionExposiciones.setText("Exposiciones");
        mostrarGestionExposiciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarGestionExposicionesActionPerformed(evt);
            }
        });
        jMenu2.add(mostrarGestionExposiciones);

        mostrarGestionEntradas.setText("Entradas");
        mostrarGestionEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarGestionEntradasActionPerformed(evt);
            }
        });
        jMenu2.add(mostrarGestionEntradas);

        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btAnnadirGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAnnadirGuiaActionPerformed
        contratar();
    }//GEN-LAST:event_btAnnadirGuiaActionPerformed

    private void btEliminarGuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarGuiaActionPerformed
        despedir();
    }//GEN-LAST:event_btEliminarGuiaActionPerformed

    private void mostrarGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarGestionEmpleadosActionPerformed
        verPanel(panelEmpleados);
    }//GEN-LAST:event_mostrarGestionEmpleadosActionPerformed

    private void mostrarGestionExposicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarGestionExposicionesActionPerformed
        verPanel(panelExposiciones);
    }//GEN-LAST:event_mostrarGestionExposicionesActionPerformed

    private void botonAbrirExpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirExpoActionPerformed
        // TODO add your handling code here:
        abrirExposicion();
    }//GEN-LAST:event_botonAbrirExpoActionPerformed

    private void botonAddExpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddExpoActionPerformed
        // TODO add your handling code here:
        annadirExposicion();
    }//GEN-LAST:event_botonAddExpoActionPerformed

    private void botonModificarExpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarExpoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarExpoActionPerformed

    private void botonDropExpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDropExpoActionPerformed
        // TODO add your handling code here:
        eliminarExposicion();
    }//GEN-LAST:event_botonDropExpoActionPerformed

    private void botonAbrirSelectorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMouseEntered
        // TODO add your handling code here:
        botonAbrirSelector.setCursor(new Cursor(HAND_CURSOR));
        botonAbrirSelector.setIcon(new ImageIcon("src/recursos/imagenes/iconos/carpetahp.png"));
    }//GEN-LAST:event_botonAbrirSelectorMouseEntered

    private void botonAbrirSelectorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMouseExited
        // TODO add your handling code here:
        botonAbrirSelector.setIcon(new ImageIcon("src/recursos/imagenes/iconos/carpeta.png"));

    }//GEN-LAST:event_botonAbrirSelectorMouseExited

    private void botonAbrirSelectorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMousePressed
        // TODO add your handling code here:
        botonAbrirSelector.setIcon(new ImageIcon("src/recursos/imagenes/iconos/carpetahp.png"));
    }//GEN-LAST:event_botonAbrirSelectorMousePressed

    private void botonAbrirSelectorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMouseReleased
        // TODO add your handling code here:
        try {
            abrirSelectorImagenes();
        } catch (IOException ex) {
            Logger.getLogger(MenuAdministradorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonAbrirSelectorMouseReleased

    private void botonAbrirSelectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMouseClicked
        // TODO add your handling code here:
        botonAbrirSelector.setIcon(new ImageIcon("src/recursos/imagenes/iconos/carpetaph.png"));
    }//GEN-LAST:event_botonAbrirSelectorMouseClicked

    private void botonAbrirExpoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirExpoMouseEntered
        // TODO add your handling code here:
        botonAbrirExpo.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonAbrirExpoMouseEntered

    private void botonAddExpoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAddExpoMouseEntered
        // TODO add your handling code here:
        botonAddExpo.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonAddExpoMouseEntered

    private void botonModificarExpoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonModificarExpoMouseEntered
        // TODO add your handling code here:
        botonModificarExpo.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonModificarExpoMouseEntered

    private void botonDropExpoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDropExpoMouseEntered
        // TODO add your handling code here:
        botonDropExpo.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonDropExpoMouseEntered

    private void btAnnadirGuiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btAnnadirGuiaMouseEntered
        // TODO add your handling code here:
        btAnnadirGuia.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btAnnadirGuiaMouseEntered

    private void btEliminarGuiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEliminarGuiaMouseEntered
        // TODO add your handling code here:
        btEliminarGuia.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_btEliminarGuiaMouseEntered

    private void botonCambiarPrecioEntradaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCambiarPrecioEntradaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCambiarPrecioEntradaMouseEntered

    private void botonCambiarSuplementoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCambiarSuplementoMouseEntered
        // TODO add your handling code here:
        cambiarPrecioSuplemento();
    }//GEN-LAST:event_botonCambiarSuplementoMouseEntered

    private void mostrarGestionEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarGestionEntradasActionPerformed
        // TODO add your handling code here:
        verPanel(panelEntradas);
    }//GEN-LAST:event_mostrarGestionEntradasActionPerformed

    private void botonCambiarPrecioEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarPrecioEntradaActionPerformed
        // TODO add your handling code here:
        cambiarPrecioEntrada();
    }//GEN-LAST:event_botonCambiarPrecioEntradaActionPerformed

    private void botonCambiarSuplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarSuplementoActionPerformed
        // TODO add your handling code here:
        cambiarPrecioSuplemento();
    }//GEN-LAST:event_botonCambiarSuplementoActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuAdministradorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAbrirExpo;
    private javax.swing.JLabel botonAbrirSelector;
    private javax.swing.JButton botonAddExpo;
    private javax.swing.JButton botonCambiarPrecioEntrada;
    private javax.swing.JButton botonCambiarSuplemento;
    private javax.swing.JButton botonDropExpo;
    private javax.swing.JToggleButton botonModificarExpo;
    private javax.swing.JButton btAnnadirGuia;
    private javax.swing.JButton btEliminarGuia;
    private javax.swing.JTextField campoDuracion;
    private javax.swing.JTextField campoNombreExpo;
    private javax.swing.JTextField campoPrecioEntrada;
    private javax.swing.JTextField campoPrecioSuplemento;
    private javax.swing.JTextField campoRuta;
    private javax.swing.JLabel infoErrorExpo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem mostrarGestionEmpleados;
    private javax.swing.JMenuItem mostrarGestionEntradas;
    private javax.swing.JMenuItem mostrarGestionExposiciones;
    private javax.swing.JLabel oblig1;
    private javax.swing.JLabel oblig2;
    private javax.swing.JLabel oblig3;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelEntradas;
    private javax.swing.JPanel panelExposiciones;
    private javax.swing.JFileChooser selectorArchivos;
    private javax.swing.JTable tablaEmpleados;
    private javax.swing.JTable tablaExposiciones;
    private javax.swing.JTextField tfClave;
    private javax.swing.JTextField tfDNI;
    private javax.swing.JTextField tfNGuia;
    private javax.swing.JTextField tfNSS;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelf;
    // End of variables declaration//GEN-END:variables

    // ####################### - Métodos Vista - #######################
    private void verPanel(JPanel jp) {
        panelEmpleados.setVisible(false);
        panelExposiciones.setVisible(false);
        panelEntradas.setVisible(false);
        datosEnBlanco();
        restablecerCamposExpo();

        jp.setVisible(true);
    }

    private void limiteTelefono(JTextField jtf) {
        final int limite = 9;
        jtf.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();

                if (jtf.getText().length() < limite) {
                    if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                            || (c == KeyEvent.VK_DELETE))) {
                        getToolkit().beep();
                        e.consume();
                    }
                } else {
                    e.consume();
                }
            }
        });
    }

    private void limiteDNI(JTextField jtf) {
        final int limite = 8;
        jtf.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();

                if (jtf.getText().length() < limite) {
                    if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                            || (c == KeyEvent.VK_DELETE))) {
                        getToolkit().beep();
                        e.consume();
                    }
                } else if (jtf.getText().length() == limite) {
                    if (!Character.isLetter(c) && !(c == KeyEvent.VK_SPACE)
                            && !(c == KeyEvent.VK_BACK_SPACE)) {
                        getToolkit().beep();
                        e.consume();
                    }
                } else {
                    e.consume();
                }
            }
        });
    }

    private static boolean validarTelefono(String tlf) {
        boolean correcto = false;
        int longitud = tlf.length();

        if (longitud == 9) {
            correcto = true;
        }

        return correcto;
    }

    private static boolean validarPassword(String pw) {
        boolean correcto = false;
        int longitud = pw.length();

        if (longitud >= 8) {
            correcto = true;
        }

        return correcto;
    }

    private void soloLetras(JTextField jtf) {
        final int limite = 30;
        jtf.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();

                if (jtf.getText().length() < limite) {
                    if (!Character.isLetter(c) && !(c == KeyEvent.VK_SPACE)
                            && !(c == KeyEvent.VK_BACK_SPACE)) {
                        getToolkit().beep();
                        e.consume();
                    }
                } else {
                    e.consume();
                }
            }
        });
    }

    private void soloNumeros(JTextField jtf) {
        jtf.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE)
                        || (c == KeyEvent.VK_DELETE))) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("recursos/imagenes/iconos/iconoMuseoApp.png"));
        return retValue;
    }

    private void conexionBD() {
        try {
            sm = new SistemaMuseo();
        } catch (SQLException ex) {
            System.out.println("Error de conexión con la Base de Datos.");
        }
    }

    private void componentesIniciales() {
        conexionBD();
        actualizarPlantilla();
        verPanel(panelEmpleados);
        limiteDNI(tfDNI);
        limiteTelefono(tfTelf);
        soloLetras(tfNombre);
        soloNumeros(tfNGuia);
        soloNumeros(tfNSS);
        soloNumeros(campoDuracion);
        oblig1.setText(" ");
        oblig2.setText(" ");
        oblig2.setText(" ");
        oblig3.setText(" ");
    }

    // ####################### - Métodos Sesion - #######################
    private void cerrarSesion() {
        MenuPrincipalFrame mpf = new MenuPrincipalFrame();
        mpf.setVisible(true);
        dispose();
    }

    // ####################### - Métodos Gestión Empleados - #######################
    private void contratar() {
        try {
            String nombre = tfNombre.getText();
            String dni = tfDNI.getText();
            String clave = tfClave.getText();
            int telefono = Integer.parseInt(tfTelf.getText());
            long nss = Long.parseLong(tfNSS.getText());
            int nGuia = Integer.parseInt(tfNGuia.getText());

            Guia g = new Guia(nombre, dni, telefono, nss, nGuia);
            a.annadirEmpleado(g);
            sm.nuevoGuia(g, clave);

            actualizarPlantilla();
            datosEnBlanco();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Campos incompletos o erroneos, itroduzca todos los datos", "Error", WIDTH);
        }
    }

    private void despedir() {

        int opcion = JOptionPane.showConfirmDialog(this, "¿Quieres despedir a este guía?");

        if (opcion == JOptionPane.YES_OPTION) {

            int seleccionado = tablaEmpleados.getSelectedRow();
            final int NOSELECCIONADO = -1;

            if (seleccionado != NOSELECCIONADO) {

                Guia aDespedir = a.getEmpleados().get(seleccionado);
                a.eliminarEmpleado(aDespedir);
                sm.despedirGuia(aDespedir);

                actualizarPlantilla();
            } else {

                JOptionPane.showMessageDialog(rootPane, "Ningún Empleado Seleccionado. Por favor, seleccione uno para despedirlo", "Advertencia", WIDTH);

            }
        }

    }

    public void actualizarPlantilla() {
        plantilla = new DefaultTableModel(a.plantillaAString(), cabeceraPlantilla);
        tablaEmpleados.setModel(plantilla);
    }

    public void datosEnBlanco() {
        tfNombre.setText("");
        tfDNI.setText("");
        tfClave.setText("");
        tfTelf.setText("");
        tfNSS.setText("");
        tfNGuia.setText("");
    }

    // ####################### - Métodos Gestión Exposiciones - #######################
    private void abrirExposicion() {
        int selection = tablaExposiciones.getSelectedRow();
        if (selection != -1) {
            Exposicion e = etm.obtenerExposicion(selection);
            ModificaExposicionDialog med = new ModificaExposicionDialog(this, true, e);
            med.setVisible(true);
        }
    }

    private void annadirExposicion() {
        if (validarDatosExposicion()) {
            Exposicion e = new Exposicion(campoNombreExpo.getName(), Integer.parseInt(campoDuracion.getText()), campoRuta.getText());
            sm.nuevaExposicion(e);
            e = sm.cargarExposicion(e.getNombre());
            etm.annadirExposicion(e);
        }
    }

    private void eliminarExposicion() {
        int selection = tablaExposiciones.getSelectedRow();

        if (selection != -1) {
            boolean salir = false;
            Exposicion e = etm.obtenerExposicion(selection);

            do {
                int opcion = JOptionPane.showConfirmDialog(this,
                        "¿Está seguro de que quiere eliminar\nla exposición \"id = "
                        + e.getID() + "\"?",
                        "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (opcion == JOptionPane.YES_OPTION) {
                    etm.eliminarExposicion(selection);
                    sm.eliminarExposicion(e.getID());
                    salir = true;
                } else if (opcion == JOptionPane.NO_OPTION) {
                    salir = true;
                }
            } while (!salir);
        }
    }

    private void modificarExposicion() {

    }

    private boolean validarDatosExposicion() {
        boolean correcto = false;

        if (!campoNombreExpo.getText().isEmpty() && !campoDuracion.getText().isEmpty() && !campoRuta.getText().isEmpty()) {
            String nombre = campoNombreExpo.getText();
            String ruta = campoRuta.getText();

            if (!sm.comprobarSiExisteExposicion(nombre)) {
                ImageIcon image = new ImageIcon(ruta);

                if (!(image.getIconHeight() <= 114 && image.getIconWidth() <= 300)) {
                    infoErrorExpo.setText("Tamaño de imagen demasiado grande.");
                } else {
                    correcto = true;
                    restablecerCamposExpo();
                    oblig1.setText(" ");
                    oblig2.setText(" ");
                    oblig2.setText(" ");
                    oblig3.setText(" ");
                }
            }
        } else {
            if (campoNombreExpo.getText().isEmpty()) {
                oblig1.setText("*");
            }

            if (campoDuracion.getText().isEmpty()) {
                oblig2.setText("*");
            }

            if (campoRuta.getText().isEmpty()) {
                oblig3.setText("*");
            }
        }

        return correcto;
    }

    private void restablecerCamposExpo() {
        campoNombreExpo.setText("");
        campoDuracion.setText("");
        campoRuta.setText("");
    }

    private void abrirSelectorImagenes() throws IOException {
        //Filtro para archivos con extension .png y .jpg
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes(*.png) y (*.jpg)", "png", "jpg");
        selectorArchivos.setFileFilter(filtro);
        selectorArchivos.setDialogTitle("Selector de archivos");
        selectorArchivos.setCurrentDirectory(new File("src/recursos/imagenes/exposiciones"));

        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = selectorArchivos.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File file = selectorArchivos.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getPath());

            if (image.getIconHeight() <= 114 && image.getIconWidth() <= 300) {
                campoRuta.setText("src/recursos/imagenes/exposiciones/" + file.getName());
                infoErrorExpo.setText(" ");
            } else {
                infoErrorExpo.setText("¡Tamaño de imagen demasiado grande!");
            }
        }
    }

    // ####################### - Métodos Gestión Entradas - #######################
    private void cambiarPrecioEntrada() {
        if (!campoPrecioEntrada.getText().isEmpty()) {
            float precio = Float.valueOf(campoPrecioEntrada.getText());
            sm.cambiarPrecioEntrada(precio);
        }
    }

    private void cambiarPrecioSuplemento() {
        if (!campoPrecioSuplemento.getText().isEmpty()) {
            float precio = Float.valueOf(campoPrecioSuplemento.getText());
            sm.cambiarPrecioSuplemento(precio);
        }
    }
}
