/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.SistemaMuseo;
import disenno.ExposicionTableModel;
import modelo.Exposicion;
import modelo.Obra;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.*;
import java.io.File;
import java.util.List;

import static java.awt.Frame.HAND_CURSOR;

/**
 * @author Victor
 */
public class ModificaExposicionDialog extends javax.swing.JDialog {

    private Exposicion exposicion;
    private List<Obra> obras;
    private ExposicionTableModel exposicionTableModel;
    private SistemaMuseo sistemaMuseo;

    /**
     * Creates new form ModExposicionesJD
     *
     * @param parent
     * @param modal
     * @param exposicion
     */
    ModificaExposicionDialog(java.awt.Frame parent, boolean modal, Exposicion exposicion) {
        super(parent, modal);
        this.exposicion = exposicion;
        obras = exposicion.getObras();
        exposicionTableModel = new ExposicionTableModel(obras);

        initComponents();
        componentesIniciales();
    }

    private ModificaExposicionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectorArchivos = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaObras = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        botonAddObra = new javax.swing.JButton();
        botonEliminarObra = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        campoAutor = new javax.swing.JTextField();
        campoRuta = new javax.swing.JTextField();
        botonAbrirSelector = new javax.swing.JLabel();
        infoErrorObra = new javax.swing.JLabel();
        oblig1 = new javax.swing.JLabel();
        oblig2 = new javax.swing.JLabel();
        oblig3 = new javax.swing.JLabel();
        oblig4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoEstilo = new javax.swing.JTextField();
        campoAnno = new javax.swing.JTextField();
        campoTipo = new javax.swing.JTextField();
        oblig5 = new javax.swing.JLabel();
        oblig6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Museo Palentino - Menu de Administrador/Exposición " + exposicion.getNombre());
        setIconImage(getIconImage());
        setResizable(false);

        tablaObras.setModel(exposicionTableModel);
        jScrollPane2.setViewportView(tablaObras);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Opciones de Obra  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        botonAddObra.setText("Añadir Obra");
        botonAddObra.setPreferredSize(new java.awt.Dimension(150, 23));
        botonAddObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAddObraMouseEntered(evt);
            }
        });
        botonAddObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAddObraActionPerformed(evt);
            }
        });

        botonEliminarObra.setText("Eliminar Obra");
        botonEliminarObra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEliminarObraMouseEntered(evt);
            }
        });
        botonEliminarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarObraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botonAddObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonEliminarObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botonAddObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonEliminarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Datos de Obra  ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel6.setText("Titulo de la obra:");

        jLabel7.setText("Autor:");

        jLabel8.setText("Estilo:");
        jLabel8.setToolTipText("");

        jLabel11.setText("Ruta de imagen (máx. 230x165 px):");
        jLabel11.setToolTipText("");

        campoRuta.setMaximumSize(new java.awt.Dimension(302, 28));
        campoRuta.setMinimumSize(new java.awt.Dimension(302, 28));
        campoRuta.setName(""); // NOI18N
        campoRuta.setPreferredSize(new java.awt.Dimension(302, 28));

        botonAbrirSelector.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imagenes/iconos/carpeta.png"))); // NOI18N
        botonAbrirSelector.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMouseExited(evt);
            }

            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMousePressed(evt);
            }

            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonAbrirSelectorMouseReleased(evt);
            }
        });

        infoErrorObra.setForeground(java.awt.Color.red);
        infoErrorObra.setText(" ");

        oblig1.setBackground(new java.awt.Color(255, 255, 255));
        oblig1.setForeground(new java.awt.Color(255, 0, 102));
        oblig1.setText("*");

        oblig2.setBackground(new java.awt.Color(255, 255, 255));
        oblig2.setForeground(new java.awt.Color(255, 0, 102));
        oblig2.setText("*");

        oblig3.setBackground(new java.awt.Color(255, 255, 255));
        oblig3.setForeground(new java.awt.Color(255, 0, 102));
        oblig3.setText("*");

        oblig4.setBackground(new java.awt.Color(255, 255, 255));
        oblig4.setForeground(new java.awt.Color(255, 0, 102));
        oblig4.setText("*");

        jLabel1.setText("Año:");

        jLabel2.setText("Tipo:");

        oblig5.setBackground(new java.awt.Color(255, 255, 255));
        oblig5.setForeground(new java.awt.Color(255, 0, 102));
        oblig5.setText("*");

        oblig6.setBackground(new java.awt.Color(255, 255, 255));
        oblig6.setForeground(new java.awt.Color(255, 0, 102));
        oblig6.setText("*");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(infoErrorObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addGap(10, 10, 10)
                                                                .addComponent(oblig3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel6)
                                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                                .addComponent(jLabel7)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(oblig2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(oblig1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(oblig4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(oblig5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(campoTipo, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(campoAnno)
                                                        .addComponent(campoAutor)
                                                        .addComponent(campoEstilo)
                                                        .addComponent(campoTitulo)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(oblig6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                                .addComponent(campoRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(botonAbrirSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(oblig1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(oblig2)
                                        .addComponent(jLabel7))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8)
                                        .addComponent(oblig3)
                                        .addComponent(campoEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(campoAnno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(oblig4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2)
                                        .addComponent(oblig5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(oblig6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botonAbrirSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(campoRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(infoErrorObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAddObraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAddObraMouseEntered
        // TODO add your handling code here:
        botonAddObra.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonAddObraMouseEntered

    private void botonAddObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAddObraActionPerformed
        // TODO add your handling code here:
        annadirObra();
    }//GEN-LAST:event_botonAddObraActionPerformed

    private void botonEliminarObraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEliminarObraMouseEntered
        // TODO add your handling code here:
        botonEliminarObra.setCursor(new Cursor(HAND_CURSOR));
    }//GEN-LAST:event_botonEliminarObraMouseEntered

    private void botonEliminarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarObraActionPerformed
        // TODO add your handling code here:
        eliminarObra();
    }//GEN-LAST:event_botonEliminarObraActionPerformed

    private void botonAbrirSelectorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMouseClicked
        // TODO add your handling code here:
        botonAbrirSelector.setIcon(new ImageIcon(getClass().getResource(("/recursos/imagenes/iconos/carpetaph.png"))));
    }//GEN-LAST:event_botonAbrirSelectorMouseClicked

    private void botonAbrirSelectorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMouseEntered
        // TODO add your handling code here:
        botonAbrirSelector.setCursor(new Cursor(HAND_CURSOR));
        botonAbrirSelector.setIcon(new ImageIcon(getClass().getResource(("/recursos/imagenes/iconos/carpetahp.png"))));
    }//GEN-LAST:event_botonAbrirSelectorMouseEntered

    private void botonAbrirSelectorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMouseExited
        // TODO add your handling code here:
        botonAbrirSelector.setIcon(new ImageIcon(getClass().getResource(("/recursos/imagenes/iconos/carpeta.png"))));
    }//GEN-LAST:event_botonAbrirSelectorMouseExited

    private void botonAbrirSelectorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMousePressed
        // TODO add your handling code here:
        botonAbrirSelector.setIcon(new ImageIcon(getClass().getResource(("/recursos/imagenes/iconos/carpetahp.png"))));
    }//GEN-LAST:event_botonAbrirSelectorMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificaExposicionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificaExposicionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificaExposicionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificaExposicionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ModificaExposicionDialog dialog = new ModificaExposicionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void botonAbrirSelectorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAbrirSelectorMouseReleased
        // TODO add your handling code here:
        abrirSelectorImagenes();
    }//GEN-LAST:event_botonAbrirSelectorMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botonAbrirSelector;
    private javax.swing.JButton botonAddObra;
    private javax.swing.JButton botonEliminarObra;
    private javax.swing.JTextField campoAnno;
    private javax.swing.JTextField campoAutor;
    private javax.swing.JTextField campoEstilo;
    private javax.swing.JTextField campoRuta;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JLabel infoErrorObra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel oblig1;
    private javax.swing.JLabel oblig2;
    private javax.swing.JLabel oblig3;
    private javax.swing.JLabel oblig4;
    private javax.swing.JLabel oblig5;
    private javax.swing.JLabel oblig6;
    private javax.swing.JFileChooser selectorArchivos;
    private javax.swing.JTable tablaObras;
    // End of variables declaration//GEN-END:variables

    // ############################# COMPONENTES INICIALES #############################
    private void componentesIniciales() {
        conexionBD();
        oblig1.setText(" ");
        oblig2.setText(" ");
        oblig3.setText(" ");
        oblig4.setText(" ");
        oblig5.setText(" ");
        oblig6.setText(" ");
    }

    // ############################# MÉTODOS MODIFICAR EXPOSICIÓN #############################
    private void annadirObra() {
        if (validarDatosExposicion()) {
            Obra obra = new Obra(campoTitulo.getText(), campoAutor.getText(), campoEstilo.getText(), campoAnno.getText(), campoTipo.getText(), campoRuta.getText(), exposicion.getID());
            sistemaMuseo.nuevaObra(obra);
            obras = sistemaMuseo.cargarObrasExposicion(exposicion.getID());
            exposicionTableModel = new ExposicionTableModel(obras);
            tablaObras.setModel(exposicionTableModel);
            restablecerCamposObra();
        }
    }

    private void eliminarObra() {
        int selection = tablaObras.getSelectedRow();

        if (selection != -1) {
            boolean salir = false;
            Obra obra = exposicionTableModel.obtenerObra(selection);

            do {
                int opcion = JOptionPane.showConfirmDialog(this,
                        "¿Está seguro de que quiere eliminar\nla obra cuyo ID es  \""
                                + obra.getId() + "\"?",
                        "Advertencia", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

                if (opcion == JOptionPane.YES_OPTION) {
                    exposicionTableModel.eliminarObra(selection);
                    sistemaMuseo.eliminarObra(obra.getId());
                    salir = true;
                } else if (opcion == JOptionPane.NO_OPTION) {
                    salir = true;
                }
            } while (!salir);
        }
    }

    private void abrirSelectorImagenes() {
        // Filtro para archivos con extension .png y .jpg
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes(*.png) y (*.jpg)", "png", "jpg");
        selectorArchivos.setFileFilter(filtro);
        selectorArchivos.setDialogTitle("Selector de archivos");
        selectorArchivos.setCurrentDirectory(new File(getClass().getProtectionDomain().getCodeSource().getLocation().getPath() + "recursos/imagenes/obras/"));

        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = selectorArchivos.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File file = selectorArchivos.getSelectedFile();
            ImageIcon image = new ImageIcon(file.getPath());

            if (image.getIconHeight() <= 165 && image.getIconWidth() <= 230) {
                campoRuta.setText("recursos/imagenes/obras/" + file.getName());
                infoErrorObra.setText(" ");
            } else {
                infoErrorObra.setText("¡Tamaño de imagen demasiado grande!");
            }
        }
    }

    private boolean validarDatosExposicion() {
        boolean correcto = false;

        if (!campoTitulo.getText().isEmpty() && !campoAutor.getText().isEmpty() && !campoEstilo.getText().isEmpty()
                && !campoAnno.getText().isEmpty() && !campoTipo.getText().isEmpty() && !campoRuta.getText().isEmpty()) {
            String titulo = campoTitulo.getText();
            String autor = campoAutor.getText();
            String anno = campoAnno.getText();
            String tipo = campoTipo.getText();
            String ruta = campoRuta.getText();

            if (!sistemaMuseo.comprobarSiExisteObra(titulo, autor, anno, tipo)) {
                File file = new File(getClass().getProtectionDomain().getCodeSource().getLocation().getPath() + ruta);
                if (!file.exists()) { // Si no existe la ruta
                    infoErrorObra.setText("¡La imagen seleccionada no existe!");
                } else {
                    correcto = true;
                    oblig1.setText(" ");
                    oblig2.setText(" ");
                    oblig3.setText(" ");
                    oblig4.setText(" ");
                    oblig5.setText(" ");
                    oblig6.setText(" ");
                }

            } else {
                JOptionPane.showMessageDialog(this, "Ya existe una obra con \nesos datos en el Museo.", "Error al añadir obra",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            if (campoTitulo.getText().isEmpty()) {
                oblig1.setText("*");
            }

            if (campoAutor.getText().isEmpty()) {
                oblig2.setText("*");
            }

            if (campoEstilo.getText().isEmpty()) {
                oblig3.setText("*");
            }

            if (campoAnno.getText().isEmpty()) {
                oblig4.setText("*");
            }

            if (campoTipo.getText().isEmpty()) {
                oblig5.setText("*");
            }

            if (campoRuta.getText().isEmpty()) {
                oblig6.setText("*");
            }
        }

        return correcto;
    }

    private void restablecerCamposObra() {
        campoTitulo.setText(null);
        campoAutor.setText(null);
        campoEstilo.setText(null);
        campoAnno.setText(null);
        campoTipo.setText(null);
        campoRuta.setText(null);
    }

    public Image getIconImage() {
        return Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/imagenes/iconos/iconoMuseoApp.png"));
    }

    // ############################# CONEXIÓN BASE DE DATOS #############################
    private void conexionBD() {
        sistemaMuseo = new SistemaMuseo();
    }
}
